AWSTemplateFormatVersion: "2010-09-09"
Description: "BSM Cloud Formation"
Parameters:
  SourceCodeBucket:
    Type: String
    Default: repo.bsm.pub
  AZ:
    Type: String
    Default: eu-central-1a
  OperatorEMail:
    Description: EMail address to notify if there are any scaling operations
    Type: String
    AllowedPattern: "([a-zA-Z0-9_\\-\\.]+)@((\\[[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.)|(([a-zA-Z0-9\\-]+\\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\\]?)"
  OpenApiHttpPort:
    Type: String
    Default: '5000'

Resources:

  NotificationTopic:
      Type: AWS::SNS::Topic
      Properties:
        Subscription:
        - Endpoint:
            Ref: OperatorEMail
          Protocol: email

  bsmDNS:
      Type: AWS::Route53::RecordSetGroup
      Properties:
        HostedZoneName: bsm.pub.
        Comment: Zone apex alias targeted to BSM LoadBalancer.
        RecordSets:
        - Name: bsm.pub.
          Type: A
          AliasTarget:
            HostedZoneId: !GetAtt bsmELB.CanonicalHostedZoneNameID
            DNSName: !GetAtt bsmELB.DNSName

  bsmELB:
    Type: AWS::ElasticLoadBalancing::LoadBalancer
    Properties:
      AvailabilityZones:
        Fn::GetAZs: ''
      CrossZone: 'true'
      Listeners:
      - LoadBalancerPort: '80'
        InstancePort:
          Ref: OpenApiHttpPort
        Protocol: HTTP
      HealthCheck:
        Target: 
          Fn::Join:
          - ''
          - - 'HTTP:'
            - Ref: OpenApiHttpPort
            - '/api/swagger-ui.html'
        HealthyThreshold: '3'
        UnhealthyThreshold: '2'
        Interval: '30'
        Timeout: '5'

  OpenApiASG:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AvailabilityZones:
        Fn::GetAZs: ''
      LaunchConfigurationName:
        Ref: OpenApiLaunchConfig
      MinSize: '1'
      MaxSize: '3'
      LoadBalancerNames:
      - Ref: bsmELB
      NotificationConfiguration:
        TopicARN:
          Ref: NotificationTopic
        NotificationTypes:
        - autoscaling:EC2_INSTANCE_LAUNCH
        - autoscaling:EC2_INSTANCE_LAUNCH_ERROR
        - autoscaling:EC2_INSTANCE_TERMINATE
        - autoscaling:EC2_INSTANCE_TERMINATE_ERROR
    CreationPolicy:
      ResourceSignal:
          Timeout: PT15M
          Count: '1'
    UpdatePolicy:
      AutoScalingRollingUpdate:
        MinInstancesInService: '1'
        MaxBatchSize: '1'
        PauseTime: PT15M
        WaitOnResourceSignals: 'true'

  OpenApiScaleUpPolicy:
      Type: AWS::AutoScaling::ScalingPolicy
      Properties:
        AdjustmentType: ChangeInCapacity
        AutoScalingGroupName:
          Ref: OpenApiASG
        Cooldown: '60'
        ScalingAdjustment: '1'

  OpenApiScaleDownPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AdjustmentType: ChangeInCapacity
      AutoScalingGroupName:
        Ref: OpenApiASG
      Cooldown: '60'
      ScalingAdjustment: "-1"

  CPUAlarmHigh:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Scale-up if CPU > 50% for 1 minute
      MetricName: CPUUtilization
      Namespace: AWS/EC2
      Statistic: Average
      Period: '60'
      EvaluationPeriods: '2'
      Threshold: '50'
      AlarmActions:
      - Ref: OpenApiScaleUpPolicy
      Dimensions:
      - Name: AutoScalingGroupName
        Value:
          Ref: OpenApiASG
      ComparisonOperator: GreaterThanThreshold

  CPUAlarmLow:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Scale-down if CPU < 50% for 1 minute
      MetricName: CPUUtilization
      Namespace: AWS/EC2
      Statistic: Average
      Period: '60'
      EvaluationPeriods: '2'
      Threshold: '50'
      AlarmActions:
      - Ref: OpenApiScaleDownPolicy
      Dimensions:
      - Name: AutoScalingGroupName
        Value:
          Ref: OpenApiASG
      ComparisonOperator: LessThanThreshold

  OpenApiSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access and HTTP from the load balancer only
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        FromPort: '22'
        IpProtocol: tcp
        ToPort: '22'
      - IpProtocol: tcp
        FromPort:
          Ref: OpenApiHttpPort
        ToPort:
          Ref: OpenApiHttpPort
        SourceSecurityGroupOwnerId:
          Fn::GetAtt:
          - bsmELB
          - SourceSecurityGroup.OwnerAlias
        SourceSecurityGroupName:
          Fn::GetAtt:
          - bsmELB
          - SourceSecurityGroup.GroupName

  #Application source code repository access
  RootRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Principal:
              Service:
              - ec2.amazonaws.com
            Action:
            - sts:AssumeRole
        Path: "/"
        Policies:
        - PolicyName: root
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - s3:Get*
              - s3:List*
              Resource:
                Fn::Join:
                - ''
                - - 'arn:aws:s3:::'
                  - Ref: SourceCodeBucket
                  - "/*"

  RootInstanceProfile:
      Type: AWS::IAM::InstanceProfile
      Properties:
        Path: "/"
        Roles:
        - Ref: RootRole

  OpenApiLaunchConfig:
      Type: AWS::AutoScaling::LaunchConfiguration
      Properties:
        KeyName: MasterKeyBSM
        ImageId: ami-07f1fbbff759e24dd
        SecurityGroups:
        - Ref: OpenApiSecurityGroup
        InstanceType: t2.micro
        IamInstanceProfile:
          Ref: RootInstanceProfile
        UserData: IyEvdXNyL2Jpbi9lbnYgYmFzaApjdXJsIC1PIGh0dHBzOi8vZG93bmxvYWQuamF2YS5uZXQvamF2YS9HQS9qZGsxMS8xMy9HUEwvb3Blbmpkay0xMS4wLjFfbGludXgteDY0X2Jpbi50YXIuZ3oKdGFyIHp4dmYgb3Blbmpkay0xMS4wLjFfbGludXgteDY0X2Jpbi50YXIuZ3oKc3VkbyBtdiBqZGstMTEuMC4xIC91c3IvbG9jYWwvCmVjaG8gJ2V4cG9ydCBKQVZBX0hPTUU9L3Vzci9sb2NhbC9qZGstMTEuMC4xO2V4cG9ydCBQQVRIPSRQQVRIOiRKQVZBX0hPTUUvYmluJyB8IHN1ZG8gdGVlIC9ldGMvcHJvZmlsZS5kL2pkazExLnNoCnNvdXJjZSAvZXRjL3Byb2ZpbGUuZC9qZGsxMS5zaAphd3MgczMgY3AgczM6Ly9yZXBvLmJzbS5wdWIvcmVsZWFzZS9jb20vYnNtL2FwcGxpY2F0aW9uLzAuMC4yMi9hcHBsaWNhdGlvbi0wLjAuMjIuamFyIC9ob21lL2VjMi11c2VyL2FwcGxpY2F0aW9uLTAuMC4yMi5qYXIKbm9odXAgamF2YSAtamFyIGFwcGxpY2F0aW9uLTAuMC4yMi5qYXI=
#        Fn::Base64:
#          Fn::Join:

Outputs:
  URL:
    Description: The URL of the website
    Value:
      Fn::Join:
      - ''
      - - http://
        - Fn::GetAtt:
          - bsmELB
          - DNSName
