AWSTemplateFormatVersion: "2010-09-09"
Description:
Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: eu-central-1
      ImageId: ami-a4c7edb2
      InstanceType: t2.micro
