AWSTemplateFormatVersion: "2010-09-09"
Description: "test jenkins cloud formation"
Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: eu-central-1a
      ImageId: ami-a4c7edb2
      InstanceType: t2.micro
